services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false

  WapplerSystems\Cleverreach\Service\ConfigurationService:
    public: true

  WapplerSystems\Cleverreach\CleverReach\Api:
    public: true